### ISSUE TITLE
How do you close the launchpad?

### ISSUE THREAD

**Issue by npearson72** [milan102/Ubuntu-Launchpad#1]
First of all, thank you for developing this. Works very nicely and is exactly what I've been looking for.

I'm wondering two things:

1. How do you close it without selecting an application? I have to hit <esc> multiple times. Is there a better way?
2. I've been able to hide the Unity Dash from the Launchpad, but when I open and close the animation effect of the icons appearing is still there. You know of anyway to disable that animation?

Thanks

**Comment by milanify** [comment]
Hello,

1) To close it without selecting an application, hit the ESC key on your keyboard.

2) Usually what I do after clicking Launchpad is move my mouse to the upper leftmost corner of the screen to return to the desktop, there is no animation if you do this.
