### ISSUE TITLE
Application not launching

### ISSUE THREAD

**Issue by lillian-alicia** [milan102/Ubuntu-Launchpad#2]
Lauchpad does not open when on the Plank panel. 

I have installed the latest version if Launchpad.

Any help would be apreciated

Thanks.

**Comment by milanify** [comment]
You followed the install instructions here, right? https://github.com/milan102/Ubuntu-Launchpad 

Is your super key (aka Windows key) on your keyboard working? Try manually doing Super Key + A on your keyboard and see if that works. I tested on Ubuntu 18.0.4 and I was able to successfully execute Launchpad from the Plank dock.

Also if your super key isn't working try this https://askubuntu.com/questions/1231863/super-key-not-working-in-ubuntu-20-04

**Comment by milanify** [comment]
@Solarapollo05 pinging you directly in case you don't get a notification

**Comment by lillian-alicia** [comment]
Thanks! I'll try that in the morning but I think you are right - it was searching for "a" on my file manager app when i pressed super + a.

**Comment by lillian-alicia** [comment]
Updating hasn't fixed this issue. Is there any way to run it through the terminal?

**Comment by milanify** [comment]
In a terminal do:

_gtk-launch "name-of-app"_ 


where "name-of-app" is the file name of the .desktop file, with or without the .desktop extension.

**Comment by lillian-alicia** [comment]
Thanks, I will try that later.

**Comment by lillian-alicia** [comment]
Running launchpad types the letter 'a' and then exits

**Comment by milanify** [comment]
That's odd, but seems like the keyboard shortcut is not being invoked properly. The program itself is a simple bash script that runs the following:

```

#!/bin/bash
xdotool keydown Super key a
sleep 0.1
xdotool keyup Super
```
Xdotool is not working properly for you, for some reason

**Comment by lillian-alicia** [comment]
I will try re-installing xdotool

**Comment by lillian-alicia** [comment]
That still didn't work. Is there any way to open launchpad without using Super + a?

**Comment by milanify** [comment]
Try to figure out what keyboard shortcut can be used to open your ubunutu applications list, if there is no way to use keyboard shortcuts to open your applications list then I'm afraid it will be more complex for a program to try to open it on its own

**Comment by lillian-alicia** [comment]
Thanks for your help anyway!
